### ISSUE TITLE
Actual TypeScript support

### ISSUE THREAD

**Issue by aaroncameron21** [evanshortiss/binance.js#2]
Your node package does not include typescript support. I'd love to use this but despite being *written* in TypeScript you don't actually provide the TypeScript in the npm module.

**Comment by evanshortiss** [comment]
@aaroncameron21 can you be more specific please?

I just tested like so and all is fine:

```
mkdir binance-test
cd binance-test
npm init
npm i @evanshortiss/binance.js -S && npm i typescript -D
```

I then created a typical `tsconfig.json` and an `index.ts` with the contents below and compiled it. Please check your environment and reopen this issue if you can provide specifics.

```ts
import * as Binance from '@evanshortiss/binance.js'

const client = new Binance.RestClient({
    apikey: 'AN API KEY'
})

client.getAllPrices().then((result) => console.log(result))
```

**Comment by evanshortiss** [comment]
Also, be sure your editor isn't simply hiding the `d.ts` files. They are definitely included in the package. The actual TS files themselves aren't included since that's unnecessary, unless perhaps you can explain a use case for including them.

**Comment by evanshortiss** [comment]
Just noticed the README references to the module name were missing the `@evanshortiss` prefix, so maybe you meant to open this issue with another similarly named module?
